#!/bin/bash

# Please
alias please='sudo "$BASH" -c "$(history -p !!)"'

# Shell  
alias ls='ls --color=auto'
alias la='ls -al --color=auto'
alias al='ls -ral --color=auto'
alias l='ls'
alias s='ls -r'

# Git
alias status='git status'
alias commit='git commit'
alias add='git add'
alias gdiff='less -R - <<< "$(git -c color.ui=always status --short)"; git diff -- '
alias glog='less -R - <<< "$(git -c color.ui=always log -a --oneline)"'

# Misc
alias core=code
alias alisa=alias
alias plan='vim +set\ ft=todo ~/.plan'
alias adventure='vim "~/adventures/$(date).txt"'
alias today='date;cal'

# Windows
alias explorer="explorer.exe"

# Arch Linux
alias ayy="yay -S"
alias yeet="yay -Rns"
alias hc=herbstclient

# Files
alias cp="cp -vi"
alias df=duf||df
alias open=xdg-open

# WM Stuff
alias autostart="$VISUAL --new-window $HOME/dots $HOME/.config/herbstluftwm/autostart"
alias aliases="$VISUAL $HOME/.config/aliases && source $HOME/.config/aliases"
alias exports="$VISUAL $HOME/.config/exports && source $HOME/.config/exports"
alias dots="cd $HOME/dots && tree -aL 2 -I '.git' $HOME/dots 2&>/dev/null || ls -AL ./**"

alias opencodec="$VISUAL --new-window $HOME/dots $HOME/.config/opencode/opencode.json"

alias development="cd $HOME/development && ls -l */ && git status"
alias system="cd $HOME/development/system && ls -l */ && git status"

alias personal="cd $HOME/personal && ls -l */ && git status"
alias website="cd $HOME/personal/website && ls -l */ && git status"

# Quick changedir 
alias ..="cd .."
alias ~~="cd -"
alias back="cd -"
alias up="cd .."
alias home="cd ~"

# General Quickopen
alias o="$EDITOR"
alias odot="$EDITOR $NEW_WINDOW"

# AI/Development
alias letsgo="opencode --continue"
alias plan="task"