#!/bin/bash

# Please
alias please='sudo "$BASH" -c "$(history -p !!)"'

# Shell  
alias ls='ls --color=auto'
alias la='ls -al --color=auto'
alias al='ls -ral --color=auto'
alias l='ls'
alias s='ls -r'

# WM Stuff
alias sxhkdrc="vim $HOME/.config/sxhkd"
alias bspwmrc="$EDITOR $HOME/.config/bspwm"
alias wmrc="$EDITOR $HOME/.config/herbstluftwm/autostart"
alias sx="sxhkd"
alias bs="bspwm"

# Git
alias status='git status'
alias commit='git commit'
alias add='git add'
alias diff~='less -R - <<< "$(git -c color.ui=always status --short)" && git diff -- '

# Misc
alias core=code
alias alisa=alias
alias plan='vim +set\ ft=todo ~/.plan'
alias adventure='vim "~/adventures/$(date).txt"'
alias today='date;cal'

# Windows
alias explorer="explorer.exe"

# Arch Linux
alias ayy="yay -S"
alias yeet="yay -Rns"
alias hc=herbstclient

# Files
alias cd..="cd .."
alias cp="cp -vi"
alias df=duf||df
alias open=xdg-open

# Quicklinks
alias aliases="$VISUAL $HOME/.config/aliases && source $HOME/.config/aliases"
alias exports="$VISUAL $HOME/.config/exports && source $HOME/.config/exports"
alias dots="cd $HOME/dots && tree -aL 2 -I '.git' $HOME/dots"
alias go-dots="cd $HOME/dots && $VIEW $HOME/dots && ls $HOME/dots"

# Quick changedir 
alias ..="cd .."
alias ~~="cd -"
alias cd~="cd -"
alias back="cd -"
alias up="cd .."
alias home="cd ~"

# General Quickopen
alias o="$EDITOR"
alias odot="$EDITOR $NEW_WINDOW"