#!/bin/bash

# Please
alias please='sudo "$BASH" -c "$(history -p !!)"'

# Shell  
alias ls='ls --color=auto'
alias la='ls -al --color=auto'
alias al='ls -ral --color=auto'
alias l='ls'
alias s='ls -r'

# WM Stuff
alias sxhkdrc="vim $HOME/.config/sxhkd"
alias bspwmrc="$EDITOR $HOME/.config/bspwm"
alias wmrc="$EDITOR $HOME/.config/herbstluftwm/autostart"
alias sx="sxhkd"
alias bs="bspwm"

# Git
alias status='git status'
alias commit='git commit'
alias add='git add'
alias gdiff='git diff'

# Misc
alias plan='vim +set\ ft=todo ~/.plan'
alias adventure='vim "~/adventures/$(date).txt"'
alias today='date;cal'

# Windows
alias explorer="explorer.exe"

# Arch Linux
alias ayy="yay -S"
alias yeet="yay -Rns"
alias hc=herbstclient

# Files
alias cd..="cd .."
alias cp="cp -vi"
alias df=duf||df
alias open=xdg-open

# Quicklinks
alias aliases="$EDITOR $HOME/.config/aliases && source $HOME/.config/aliases"
alias exports="$EDITOR $HOME/.config/exports && source $HOME/.config/exports"
alias dots="cd $HOME/dots && $EDITOR $HOME/dots && source $HOME/.bashrc"

# Quick changedir 
alias ..="cd .."
alias ~~="cd -"
alias back="cd -"
alias up="cd .."
alias home="cd ~"

# General Quickopen
alias o="$EDITOR"
alias odot="$NEW_WINDOW"
alias alisa=aliases