#!/bin/bash
WINDOW=$(herbstclient attr clients.focus.twin)
if [[ -z "$WINDOW" ]]; then
    WINDOW=$(herbstclient list_clients | head -1)
fi
FOCUSED=$(herbstclient dump | grep -f "$WINDOW")
if [[ -n "$FOCUSED" ]]; then
    echo "$(herbstclient attr clients.$WINDOW.geometry)" | awk "{print \$1\"x\"$4\"+\"($1+\$3/2)}"
fi